"""
core/processed_publication.py

Domain entity representing a processed publication.

A ProcessedPublication encapsulates the original Publication together with
all processing Results generated by the configured Processors.

This is the primary object exchanged between the Pipeline and the Outputs.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from typing import Any

from core.publication import Publication
from core.result import Result


@dataclass(slots=True)
class ProcessedPublication:
    """
    Represents a Publication after processing.

    Attributes
    ----------
    publication : Publication
        Original collected publication.

    results : list[Result]
        Results generated by one or more Processors.

    metadata : dict[str, Any]
        Optional processing metadata.
    """

    publication: Publication

    results: list[Result] = field(default_factory=list)

    metadata: dict[str, Any] = field(default_factory=dict)

    # ------------------------------------------------------------------
    # Utility Methods
    # ------------------------------------------------------------------

    def add_result(self, result: Result) -> None:
        """
        Adds a processing result.
        """
        self.results.append(result)

    # ------------------------------------------------------------------

    def extend_results(self, results: list[Result]) -> None:
        """
        Adds multiple processing results.
        """
        self.results.extend(results)

    # ------------------------------------------------------------------

    def has_results(self) -> bool:
        """
        Returns True if at least one Result exists.
        """
        return len(self.results) > 0

    # ------------------------------------------------------------------

    def result_count(self) -> int:
        """
        Returns the total number of Results.
        """
        return len(self.results)

    # ------------------------------------------------------------------

    def keyword_results(self) -> list[Result]:
        """
        Returns one "keyword" Result per distinct keyword value.

        A Processor may generate multiple keyword Results for this
        Publication (e.g. KeywordProcessor emits one per matching
        paragraph). Displays and exports show one entry per
        publication, so this collapses repeated matches of the same
        keyword down to their first occurrence.
        """

        seen: dict[str, Result] = {}

        for result in self.results:

            if result.type != "keyword":
                continue

            if result.value not in seen:
                seen[result.value] = result

        return list(seen.values())

    # ------------------------------------------------------------------

    def deduplicated(self) -> "ProcessedPublication":
        """
        Returns a copy with repeated keyword matches collapsed via
        keyword_results(), while other result types (e.g. summary) are
        kept as-is. Intended for exports/consumers that want the same
        "one entry per publication" view the Results tab and Clipping
        already show, instead of the raw per-paragraph Result list.
        """

        other_results = [
            result
            for result in self.results
            if result.type != "keyword"
        ]

        return ProcessedPublication(
            publication=self.publication,
            results=self.keyword_results() + other_results,
            metadata=self.metadata,
        )

    # ------------------------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """
        Converts the ProcessedPublication into a dictionary.
        """

        return {
            "publication": self.publication.to_dict(),
            "results": [
                result.to_dict()
                for result in self.results
            ],
            "metadata": self.metadata,
        }

    # ------------------------------------------------------------------

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ProcessedPublication":
        """
        Creates a ProcessedPublication from a dictionary.
        """

        publication = Publication.from_dict(
            data["publication"]
        )

        results = [
            Result.from_dict(item)
            for item in data.get("results", [])
        ]

        metadata = data.get("metadata", {})

        return cls(
            publication=publication,
            results=results,
            metadata=metadata,
        )

    # ------------------------------------------------------------------

    def to_json(
        self,
        indent: int = 4,
        ensure_ascii: bool = False,
    ) -> str:
        """
        Serializes the ProcessedPublication to JSON.
        """

        return json.dumps(
            self.to_dict(),
            indent=indent,
            ensure_ascii=ensure_ascii,
        )

    # ------------------------------------------------------------------

    def __str__(self) -> str:
        return (
            f"ProcessedPublication("
            f"title='{self.publication.title}', "
            f"results={len(self.results)})"
        )